<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class Portal extends BaseConfig
{
    /**
     * Public editorial content adapted from the approved HTML mockups.
     *
     * @var array<string, array<string, mixed>>
     */
    public array $categories = [
        'cocineras-cocineros-tradicionales' => [
            'number'      => '01',
            'name'        => 'Cocineras y Cocineros Tradicionales',
            'shortName'   => 'Cocineras tradicionales',
            'accent'      => 'wine',
            'image'       => 'hero-cocineras.png',
            'cardImage'   => 'categoria-cocineras.png',
            'eyebrow'     => 'Convocatoria estatal · Categoría 01',
            'subtitle'    => 'Saberes, recetas y técnicas que mantienen viva nuestra identidad.',
            'description' => 'Reconocemos a quienes preservan y comparten la cocina tradicional de las regiones del Estado de México.',
            'introTitle'  => 'Una cocina que cuenta nuestra historia',
            'intro'       => 'Buscamos cocineras y cocineros portadores de recetas, técnicas, ingredientes y memorias comunitarias. Su propuesta deberá expresar el arraigo familiar, municipal y cultural de la cocina mexiquense.',
            'facts'       => [
                ['title' => '¿Quiénes participan?', 'text' => 'Personas mayores de edad residentes del Estado de México con trayectoria en cocina tradicional.'],
                ['title' => '¿Qué debes presentar?', 'text' => 'Expediente, carta de motivos, video y la información de una receta o platillo insignia.'],
                ['title' => '¿Qué se evaluará?', 'text' => 'Autenticidad, preservación, legado familiar, identidad, presentación e impacto cultural.'],
                ['title' => 'Representa al Estado de México', 'text' => 'Las personas seleccionadas formarán parte de la presencia gastronómica mexiquense rumbo a París 2026.'],
            ],
            'steps' => [
                ['number' => '01', 'title' => 'Registro digital', 'text' => 'Captura tus datos y reúne la documentación solicitada.'],
                ['number' => '02', 'title' => 'Revisión documental', 'text' => 'El equipo de la convocatoria verificará que el expediente esté completo.'],
                ['number' => '03', 'title' => 'Valoración', 'text' => 'Las propuestas serán revisadas conforme a los criterios publicados.'],
                ['number' => '04', 'title' => 'Resultados', 'text' => 'Las personas seleccionadas recibirán notificación directa por correo.'],
            ],
            'requirements' => [
                'Ser mayor de 18 años y residir en alguno de los 125 municipios del Estado de México.',
                'Contar con experiencia comprobable como cocinera o cocinero tradicional.',
                'Presentar una receta o platillo vinculado con la memoria familiar o comunitaria.',
                'Tener disponibilidad para participar en las actividades derivadas de la selección.',
                'Aceptar las bases, declaraciones y tratamiento de datos de la convocatoria.',
            ],
            'documents' => [
                ['title' => 'Expediente digital', 'text' => 'Identificación, CURP, comprobante de domicilio y documentación indicada en el formulario.'],
                ['title' => 'Carta de motivos', 'text' => 'Explica tu trayectoria, vínculo con la cocina tradicional y razones para representar al estado.'],
                ['title' => 'Video de presentación', 'text' => 'Presenta tu historia, tu comunidad y la relevancia de tu práctica culinaria.'],
                ['title' => 'Información de la receta', 'text' => 'Nombre, origen, ingredientes, proceso, contexto cultural y fotografías del platillo.'],
            ],
            'criteriaTitle' => 'Seis criterios de valoración',
            'criteria' => [
                ['title' => 'Autenticidad', 'text' => 'Vínculo genuino con saberes y prácticas tradicionales.'],
                ['title' => 'Preservación', 'text' => 'Conservación de ingredientes, procesos y técnicas.'],
                ['title' => 'Legado familiar', 'text' => 'Transmisión de conocimientos entre generaciones.'],
                ['title' => 'Identidad municipal', 'text' => 'Representación del territorio y de su comunidad.'],
                ['title' => 'Presentación', 'text' => 'Claridad y calidad del expediente y del video.'],
                ['title' => 'Impacto cultural y turístico', 'text' => 'Capacidad de compartir el patrimonio gastronómico mexiquense.'],
            ],
            'benefits' => [
                'Reconocimiento como representante de la cocina tradicional mexiquense.',
                'Acompañamiento institucional durante el proceso de preparación.',
                'Participación en actividades de difusión rumbo a París 2026.',
            ],
            'faq' => [
                ['question' => '¿Puedo participar si ya concursé en otra convocatoria?', 'answer' => 'Cada persona puede registrar una sola participación en todo el programa, sin importar la categoría.'],
                ['question' => '¿Puedo guardar mi registro y continuarlo después?', 'answer' => 'Sí. Al crear el borrador recibirás un folio para continuar mientras la convocatoria permanezca abierta.'],
                ['question' => '¿Qué sucede después de enviar?', 'answer' => 'La solicitud queda bloqueada y pasa a revisión. Podrás consultar su estado mediante correo, folio y código temporal.'],
            ],
        ],
        'restaurantes' => [
            'number'      => '02',
            'name'        => 'Restaurantes',
            'title'       => 'Festival Gastronómico “Sabor a México” París 2026',
            'shortName'   => 'Restaurantes',
            'accent'      => 'gold',
            'image'       => 'categoria-restaurantes.png',
            'cardImage'   => 'categoria-restaurantes.png',
            'eyebrow'     => 'Convocatoria dirigida a restaurantes del Estado de México',
            'subtitle'    => 'La gastronomía mexiquense como puente cultural entre México y Francia.',
            'description' => 'En el marco de los 200 años de relaciones diplomáticas entre México y Francia, el Festival Internacional “Sabor a México” convoca a restaurantes establecidos en el Estado de México para representar la riqueza gastronómica mexiquense en París durante noviembre de 2026.',
            'introTitle'  => 'Proyección internacional de la gastronomía mexiquense',
            'intro'       => 'La convocatoria busca preservar, promover e innovar la cocina mexicana, fortalecer el intercambio cultural entre México y Francia y generar alianzas estratégicas para que los restaurantes amplíen su presencia nacional e internacional como embajadores de nuestra identidad gastronómica.',
            'notice'      => 'La fecha límite de inscripción y el correo electrónico oficial permanecen pendientes de confirmación.',
            'facts'       => [
                ['title' => '¿Quiénes participan?', 'text' => 'Restaurantes con uno o más establecimientos en el Estado de México y al menos cinco años de operación comprobable.'],
                ['title' => 'Cocina mexicana', 'text' => 'Establecimientos especializados en cocina mexicana que ofrezcan platillos tradicionales y de autor.'],
                ['title' => 'Representación culinaria', 'text' => 'La participación estará encabezada por un chef ejecutivo mexicano o una brigada con pasaporte vigente.'],
                ['title' => 'París · Noviembre 2026', 'text' => 'Los restaurantes seleccionados participarán en el Festival “Sabor a México” en París, Francia.'],
            ],
            'steps' => [
                ['number' => '01', 'title' => 'Registro digital', 'text' => 'Captura los datos del restaurante, del chef ejecutivo y de la propuesta gastronómica.'],
                ['number' => '02', 'title' => 'Expediente', 'text' => 'Carga licencias, evidencias, fotografías, video institucional y carta de intención.'],
                ['number' => '03', 'title' => 'Selección', 'text' => 'El comité revisará la trayectoria, identidad culinaria y propuesta presentada.'],
                ['number' => '04', 'title' => 'Festival', 'text' => 'Los restaurantes seleccionados representarán al Estado de México en París.'],
            ],
            'requirements' => [
                'Contar con uno o más establecimientos operando dentro del Estado de México.',
                'Tener un mínimo de cinco años de operación comprobable.',
                'Especializarse en cocina mexicana y ofrecer platillos tradicionales y platillos de autor.',
                'Contar con un chef ejecutivo de nacionalidad mexicana.',
                'Tener interés en promover la gastronomía mexiquense en París.',
                'Contar con pasaporte vigente del chef ejecutivo o de la brigada de cocina representante.',
                'Encontrarse al corriente en permisos, licencias y documentación oficial para operar.',
                'Presentar fotografías profesionales, video institucional y una propuesta gastronómica que represente la identidad culinaria del Estado de México.',
            ],
            'documents' => [
                ['title' => 'Documentación operativa', 'text' => 'Licencia de funcionamiento, permisos vigentes y evidencia de operación mínima de cinco años.'],
                ['title' => 'Trayectoria', 'text' => 'Captura la semblanza del restaurante en el formulario y adjunta el currículum del chef ejecutivo.'],
                ['title' => 'Identificación de la representación', 'text' => 'Copia del pasaporte vigente del chef ejecutivo o de la brigada representante.'],
                ['title' => 'Evidencia audiovisual', 'text' => 'Fotografías del establecimiento y de los platillos insignia, además de un video institucional.'],
                ['title' => 'Carta de intención', 'text' => 'Máximo dos cuartillas, en hoja membretada y firmada por propietario, representante legal o chef ejecutivo, con los ocho puntos indicados en la convocatoria.'],
                ['title' => 'Propuesta gastronómica', 'text' => 'Descripción de la identidad culinaria mexiquense, platillos insignia, tradicionales y de autor que representarán al restaurante.'],
            ],
            'additionalSections' => [
                [
                    'eyebrow' => 'Carta de intención',
                    'title' => 'Contenido obligatorio de la carta',
                    'intro' => 'Debe estar dirigida al comité organizador y firmada por el propietario, representante legal o chef ejecutivo.',
                    'items' => [
                        'Nombre del restaurante y breve reseña de su trayectoria.',
                        'Motivos por los cuales desea participar en el Festival “Sabor a México” en París.',
                        'Explicación de cómo la propuesta representa la identidad, tradición y riqueza culinaria del Estado de México.',
                        'Descripción de los platillos insignia y de autor que presentará durante el festival.',
                        'Compromiso para fungir como embajador de la gastronomía mexiquense en escenarios internacionales.',
                        'Estrategias para difundir la cultura gastronómica estatal antes, durante y después del festival.',
                        'Impacto turístico, cultural y comercial esperado para el restaurante y para el Estado de México.',
                        'Interés expreso en integrarse como aliado estratégico para la promoción internacional de la cocina mexiquense.',
                    ],
                ],
                [
                    'eyebrow' => 'Formato',
                    'title' => 'Características de la carta',
                    'intro' => 'Prepara el documento antes de comenzar la carga del expediente.',
                    'items' => [
                        'Extensión máxima de dos cuartillas.',
                        'Elaborada en hoja membretada del restaurante.',
                        'Firmada por el propietario, representante legal o chef ejecutivo.',
                        'Incluir datos de contacto oficiales del establecimiento.',
                    ],
                ],
            ],
            'criteriaEyebrow' => 'Promoción internacional',
            'criteriaTitle' => 'Estrategias de promoción internacional',
            'criteria' => [
                ['title' => 'Presentaciones y degustaciones', 'text' => 'Actividades ante medios internacionales, empresarios y operadores turísticos.'],
                ['title' => 'Contenido desde París', 'text' => 'Creación de contenido audiovisual y activaciones digitales con alcance internacional.'],
                ['title' => 'Colaboraciones culinarias', 'text' => 'Vinculación con restaurantes franceses e intercambio culinario México–Francia.'],
                ['title' => 'Difusión cultural', 'text' => 'Campañas con chefs y cocineros tradicionales, recetarios y cápsulas gastronómicas.'],
                ['title' => 'Alianzas comerciales', 'text' => 'Networking y relaciones con chefs, empresarios y representantes del sector turístico.'],
                ['title' => 'Fortalecimiento de marca', 'text' => 'Posicionamiento como referente y embajador de la cocina mexiquense.'],
            ],
            'benefits' => [
                'Promoción nacional e internacional de la marca.',
                'Participación en el Festival “Sabor a México” en París.',
                'Difusión en medios de comunicación nacionales e internacionales.',
                'Vinculación con chefs, empresarios y representantes del sector turístico.',
                'Posicionamiento como embajadores de la gastronomía mexiquense.',
                'Oportunidades de networking, alianzas comerciales y colaboraciones con restaurantes franceses.',
                'Presencia en campañas digitales, materiales promocionales y actividades culturales en Francia.',
                'Proyección turística del restaurante ante visitantes internacionales.',
            ],
            'faq' => [
                ['question' => '¿Cuándo cierra la inscripción?', 'answer' => 'La fecha límite de inscripción permanece pendiente de confirmación institucional.'],
                ['question' => '¿Quién debe firmar la carta de intención?', 'answer' => 'El propietario, representante legal o chef ejecutivo del restaurante.'],
                ['question' => '¿Qué extensión debe tener la carta?', 'answer' => 'Máximo dos cuartillas, en hoja membretada y con datos oficiales de contacto.'],
                ['question' => '¿Dónde se realizará el festival?', 'answer' => 'En París, Francia, durante noviembre de 2026.'],
            ],
            'officialLegend' => 'Los restaurantes seleccionados fungirán como embajadores gastronómicos del Estado de México, promoviendo la riqueza culinaria, cultural y turística de la entidad ante el mundo, fortaleciendo los lazos históricos entre México y Francia a través de la gastronomía.',
        ],
        'joven-talento-gastronomia' => [
            'number'      => '03',
            'name'        => 'Joven Talento Universitario en Gastronomía',
            'shortName'   => 'Joven talento',
            'accent'      => 'wine',
            'image'       => 'categoria-joven-talento.png',
            'cardImage'   => 'categoria-joven-talento.png',
            'eyebrow'     => 'Convocatoria estatal · Categoría 03',
            'subtitle'    => 'Talento joven, cocina mexiquense y técnica francesa.',
            'description' => 'Estudiantes de gastronomía compiten de manera individual con una propuesta que reúne ingredientes mexiquenses, creatividad y formación culinaria.',
            'introTitle'  => 'Talento joven, cocina mexiquense y técnica francesa',
            'intro'       => 'Cada estudiante participa de manera individual y administra su propio registro, propuesta, video y expediente. La competencia reconoce la técnica, creatividad e identidad mexiquense de cada participante.',
            'facts'       => [
                ['title' => 'Participación individual', 'text' => 'Una alumna o alumno de gastronomía por solicitud y por folio.'],
                ['title' => 'Video · máximo 3 minutos', 'text' => 'La persona participante presenta y elabora la quiché con la que competirá.'],
                ['title' => 'Gran final · 2 h 15 min', 'text' => 'Tiempo total para desarrollar el concepto gastronómico durante la competencia.'],
                ['title' => 'Canasta sorpresa', 'text' => '25 minutos para seleccionarla y 15 minutos para redactar la receta con sus ingredientes.'],
            ],
            'steps' => [
                ['number' => '01', 'title' => 'Registro individual', 'text' => 'Captura tus datos, institución educativa y propuesta de quiché.'],
                ['number' => '02', 'title' => 'Selección documental', 'text' => 'Se revisan trayectoria, carta de motivos, video y ficha técnica.'],
                ['number' => '03', 'title' => 'Reto culinario', 'text' => 'Cada estudiante seleccionado desarrolla individualmente su concepto ante el comité.'],
                ['number' => '04', 'title' => 'Resultado final', 'text' => 'La selección se comunica directamente al correo registrado.'],
            ],
            'requirements' => [
                'Participar de manera individual y ser mayor de edad.',
                'Estar inscritas o inscritos en una licenciatura en gastronomía.',
                'Pertenecer a una institución educativa ubicada en el Estado de México.',
                'Presentar un video de máximo tres minutos en el que la persona participante presente y elabore la quiché con la que competirá.',
                'No participar en otra categoría de la convocatoria.',
            ],
            'documents' => [
                ['title' => 'Expediente individual', 'text' => 'Identificación, CURP, constancia académica y documentación de la persona participante.'],
                ['title' => 'Carta de motivos', 'text' => 'Explica el interés de la persona participante y su relación con la cocina mexiquense.'],
                ['title' => 'Video de la quiché', 'text' => 'Video de máximo tres minutos donde la alumna o alumno presenta y elabora la quiché con la que competirá.'],
                ['title' => 'Ficha técnica de la quiché', 'text' => 'Ingredientes, procedimiento, costos, fotografía y justificación de la propuesta.'],
            ],
            'additionalSections' => [
                [
                    'eyebrow' => 'Reto culinario',
                    'title' => 'Tiempos de la gran final',
                    'intro' => 'La alumna o alumno desarrollará individualmente su concepto gastronómico el día de la competencia.',
                    'items' => [
                        '2 horas con 15 minutos para desarrollar el concepto gastronómico.',
                        '25 minutos para la selección de la canasta sorpresa.',
                        '15 minutos para redactar la receta del platillo con los ingredientes de la canasta sorpresa.',
                    ],
                ],
            ],
            'criteriaTitle' => 'Cómo se evalúa cada etapa',
            'criteria' => [
                ['title' => 'Identidad mexiquense', 'text' => 'Uso significativo de ingredientes y referentes del estado.'],
                ['title' => 'Técnica', 'text' => 'Dominio de procesos culinarios y ejecución.'],
                ['title' => 'Creatividad', 'text' => 'Interpretación original y coherente del reto.'],
                ['title' => 'Organización', 'text' => 'Planeación, manejo del tiempo y claridad durante la ejecución individual.'],
                ['title' => 'Viabilidad', 'text' => 'Consistencia de la ficha técnica y posibilidad de reproducción.'],
                ['title' => 'Presentación', 'text' => 'Calidad visual y argumentación de la propuesta.'],
            ],
            'benefits' => [
                'Experiencia formativa y acompañamiento durante los retos.',
                'Difusión del talento universitario y de su institución.',
                'Participación en actividades derivadas de la selección rumbo a París 2026.',
            ],
            'faq' => [
                ['question' => '¿El registro es individual?', 'answer' => 'Sí. Cada alumna o alumno registra su propia participación y recibe un folio individual.'],
                ['question' => '¿Qué debe mostrar el video?', 'answer' => 'En un máximo de tres minutos, la persona participante debe presentarse y elaborar la quiché con la que competirá.'],
                ['question' => '¿Cuánto dura el reto de la gran final?', 'answer' => 'La persona participante tendrá 2 horas con 15 minutos para desarrollar su concepto gastronómico, además de los tiempos indicados para la canasta sorpresa y la receta escrita.'],
            ],
        ],
        'bebidas-tradicionales-ancestrales' => [
            'number'      => '04',
            'name'        => 'Productoras y Productores de Bebidas Tradicionales y Ancestrales',
            'shortName'   => 'Bebidas ancestrales',
            'accent'      => 'green',
            'image'       => 'hero-bebidas.png',
            'cardImage'   => 'categoria-bebidas.png',
            'eyebrow'     => 'Convocatoria estatal · Categoría 04',
            'subtitle'    => 'Bebidas que cuentan la historia de nuestra tierra.',
            'description' => 'Reconocemos bebidas tradicionales y ancestrales elaboradas mediante procesos artesanales con arraigo comunitario.',
            'introTitle'  => 'Bebidas que cuentan la historia de nuestra tierra',
            'intro'       => 'La convocatoria reúne a productoras y productores que preservan procesos, ingredientes, conocimientos y expresiones culturales vinculadas con sus comunidades.',
            'facts'       => [
                ['title' => '¿Quiénes participan?', 'text' => 'Personas productoras del Estado de México con experiencia en bebidas tradicionales o ancestrales.'],
                ['title' => '¿Qué puedes registrar?', 'text' => 'Una bebida y su proceso, historia, origen, identidad y relación con la comunidad.'],
                ['title' => 'Experiencia comprobable', 'text' => 'La trayectoria deberá acreditarse con documentos, fotografías o evidencias verificables.'],
                ['title' => '¿Qué se evaluará?', 'text' => 'Tradición, proceso artesanal, trayectoria, identidad, presentación y proyección.'],
            ],
            'steps' => [
                ['number' => '01', 'title' => 'Registro digital', 'text' => 'Captura los datos de la persona productora, proyecto y bebida.'],
                ['number' => '02', 'title' => 'Revisión documental', 'text' => 'Se valida el expediente y la evidencia de trayectoria.'],
                ['number' => '03', 'title' => 'Valoración', 'text' => 'La bebida se revisa conforme a siete criterios publicados.'],
                ['number' => '04', 'title' => 'Resultados', 'text' => 'Las personas seleccionadas reciben una comunicación privada.'],
            ],
            'requirements' => [
                'Ser mayor de edad y residir en el Estado de México.',
                'Elaborar una bebida tradicional o ancestral mediante un proceso artesanal.',
                'Acreditar experiencia y vínculo con la comunidad o territorio.',
                'Contar con la documentación fiscal o regulatoria que corresponda.',
                'Tener disponibilidad para atender las actividades de la convocatoria.',
            ],
            'documents' => [
                ['title' => 'Expediente digital', 'text' => 'Identificación, CURP, comprobante de domicilio y datos generales del proyecto.'],
                ['title' => 'Evidencia de trayectoria', 'text' => 'Constancias, reconocimientos, publicaciones o documentos que acrediten experiencia.'],
                ['title' => 'Documento fiscal', 'text' => 'Información fiscal aplicable a la persona, marca, empresa o proyecto.'],
                ['title' => 'Video y fotografías', 'text' => 'Presentación de la bebida, proceso artesanal, entorno de producción y producto final.'],
            ],
            'criteriaTitle' => 'Siete criterios de valoración',
            'criteria' => [
                ['title' => 'Tradición y autenticidad', 'text' => 'Continuidad de saberes y prácticas del territorio.'],
                ['title' => 'Proceso artesanal', 'text' => 'Participación directa y cuidado en la elaboración.'],
                ['title' => 'Trayectoria', 'text' => 'Experiencia comprobable de la persona productora.'],
                ['title' => 'Representatividad cultural', 'text' => 'Relación con la comunidad y la identidad mexiquense.'],
                ['title' => 'Originalidad e identidad', 'text' => 'Características propias de la bebida y su relato.'],
                ['title' => 'Presentación y video', 'text' => 'Claridad y calidad de la evidencia presentada.'],
                ['title' => 'Proyección internacional', 'text' => 'Capacidad de comunicar su valor en otros contextos.'],
            ],
            'benefits' => [
                'Reconocimiento y difusión de la bebida y su proceso artesanal.',
                'Acompañamiento institucional durante la preparación.',
                'Participación en actividades derivadas de la selección rumbo a París 2026.',
            ],
            'faq' => [
                ['question' => '¿Qué bebidas pueden registrarse?', 'answer' => 'Bebidas tradicionales o ancestrales vinculadas con el Estado de México y elaboradas mediante procesos artesanales.'],
                ['question' => '¿Puedo presentar un enlace de video?', 'answer' => 'Sí. El formulario permitirá cargar un archivo MP4 o registrar una URL HTTPS válida.'],
                ['question' => '¿Los resultados serán públicos?', 'answer' => 'No habrá una lista pública. Cada persona podrá consultar su estado y recibirá comunicación por correo.'],
            ],
        ],
    ];
}
